services:
  fhir:
    build:
      context:  ./fhir-server
      dockerfile: docker/Dockerfile.fhir-server
    environment:
      - hapi.fhir.ig_runtime_upload_enabled=false
      - hapi.fhir.install_transitive_ig_dependencies=true
      - hapi.fhir.implementationguides.vbpr.name=hl7.fhir.us.davinci-vbpr
      - hapi.fhir.implementationguides.vbpr.version=1.0.0-ballot
      - hapi.fhir.implementationguides.vbpr.reloadExisting=false
      - hapi.fhir.implementationguides.vbpr.installMode=STORE_AND_INSTALL
    ports:
      - "8080:8080"
  init:
    build:
      context:  ./fhir-server
      dockerfile: docker/Dockerfile.init
    environment:
      - FHIR_PROTOCOL=https
      - FHIR_HOST=vbpr-server.davinci.hl7.org
      - FHIR_API_PORT=443
      - FHIR_API_PATH=fhir
