services:
  fhir:
    build:
      context:  ./fhir-server
      dockerfile: ./docker/Dockerfile.fhir-server
    ports:
      - "8080:8080"
  web:
    build:
      context:  ./web-app
      dockerfile: ./docker/Dockerfile.web-app
    environment:
      - FHIR_ENDPOINT=http://fhir:8080/fhir
    ports:
      - "3000:3000"
  init:
    build:
      context:  ./fhir-server
      dockerfile: ./docker/Dockerfile.init
