services:
  fhir:
    build:
      context:  ../fhir-server
      dockerfile: ../docker/Dockerfile.fhir-server
    environment:
      - spring.datasource.driverClassName=org.postgresql.Driver
      - spring.jpa.properties.hibernate.dialect=ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgres94Dialect
      - spring.jpa.properties.hibernate.search_enabled=false
      - spring.datasource.url=jdbc:postgresql://db:5432/hapi
      - spring.datasource.username=admin
      - spring.datasource.password=admin
    ports:
      - "8080:8080"
  web:
    build:
      context:  ../web-app
      dockerfile: ../docker/Dockerfile.web-app
    environment:
      - FHIR_ENDPOINT=http://fhir:8080/fhir
    ports:
      - "3000:3000"
  init:
    build:
      context:  ../fhir-server
      dockerfile: ../docker/Dockerfile.init
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: hapi
