FROM alpine:latest

ENV FHIR_PROTOCOL=http
ENV FHIR_HOST=fhir
ENV FHIR_API_PORT=8080
ENV FHIR_API_PATH=fhir

RUN apk add curl jq

WORKDIR /vbpr

ADD bin/*.sh ./
RUN chmod +x ./*.sh

ENTRYPOINT [ "/bin/sh", "/vbpr/entrypoint.sh" ]
