FROM alpine:latest

ENV FHIR_PROTOCOL=https
ENV FHIR_HOST=vbpr-server.davinci.hl7.org
ENV FHIR_API_PORT=443
ENV FHIR_API_PATH=fhir

RUN apk add curl jq

WORKDIR /vbpr

ADD bin/*.sh ./
COPY bin/init-entrypoint.sh /vbpr/entrypoint.sh
RUN chmod +x ./*.sh

ENTRYPOINT [ "/bin/sh", "/vbpr/entrypoint.sh" ]
